import React ,{Component ,useContext} from 'react' 
import {context ,channelContext} from './App'
function About() {
    const usercon=useContext(context)
    const chacon=useContext(channelContext)

    return(
        <div>Welcome From About Page
            ------------------ {usercon} -----{chacon } ----------------
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus efficitur pulvinar diam a tristique. Nunc vulputate fringilla feugiat. Maecenas quis hendrerit risus, id posuere tellus. Etiam ultricies dapibus elementum. Suspendisse potenti. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Integer blandit porta tellus eu laoreet. Phasellus vehicula, ligula vel volutpat hendrerit, ante massa interdum elit, sit amet malesuada nunc urna quis erat.

Quisque id arcu semper, dictum tortor in, mollis lacus. Integer bibendum convallis dui id tincidunt. Praesent condimentum mauris in auctor varius. Vivamus nec dui id risus pretium pulvinar et sit amet nunc. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus id arcu id eros vehicula placerat. Proin rutrum bibendum auctor. In nec scelerisque sapien. Ut vitae arcu ut eros fermentum vulputate ac vitae tortor. Nam rhoncus dui interdum scelerisque lacinia. Morbi gravida nibh a magna dapibus aliquet.

Quisque luctus vitae magna in molestie. Nulla hendrerit erat vel scelerisque tristique. Nunc placerat malesuada dolor, dictum commodo justo faucibus eu. Phasellus porttitor cursus ornare. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce eu tempus sem. Duis sollicitudin sagittis ligula, nec commodo mi eleifend et. Nullam lectus tortor, placerat ac lectus cursus, elementum porta mauris. Morbi congue sodales urna in blandit. Donec finibus eros enim, a iaculis ipsum tempus commodo. Ut at porttitor leo. Curabitur facilisis ut ipsum sit amet sagittis. Nulla rhoncus consectetur est, ut malesuada nisl tempus ut.

Sed dapibus id nisl a feugiat. Fusce rutrum nulla nisl, eu molestie purus convallis a. Proin leo velit, tempus non mi vel, tempor consequat sapien. Aliquam elit augue, pretium nec urna id, scelerisque eleifend dolor. Cras augue nisi, accumsan maximus sagittis a, aliquet ut neque. Donec tincidunt metus enim, vel tincidunt turpis congue eget. Nullam a condimentum sapien. Sed mattis pharetra velit sed fringilla. Ut eget accumsan tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce quis viverra leo. Aenean et sollicitudin felis, non aliquet metus.

Proin id fermentum sem. Quisque quis faucibus mauris. Ut in malesuada lorem. Etiam quis enim at libero commodo tempor rutrum ut eros. Vestibulum fermentum est in eros accumsan, ut sollicitudin diam ornare. Integer porta a erat non ultricies. Donec consectetur, velit a tristique accumsan, urna nisl molestie augue, ac fermentum erat neque vel elit. Vivamus egestas enim at lorem vulputate porta posuere in nunc.

Donec pharetra consectetur sem ut auctor. Vivamus vitae sapien nunc. Donec maximus erat id augue imperdiet, sed semper libero lacinia. Suspendisse potenti. Maecenas vitae sagittis felis. Pellentesque fringilla, tellus at blandit sodales, diam nunc tempus massa, nec tempor sapien justo vitae urna. Donec vehicula elit vel odio tincidunt dignissim. Etiam volutpat magna quis semper tempor. Integer placerat tempor mollis. Donec vulputate justo magna, pellentesque faucibus nibh facilisis quis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas bibendum felis eget purus pellentesque dictum. Nullam tincidunt odio urna, at mattis erat lobortis ut. Nulla porttitor quam sed nisl elementum sagittis. Sed eget metus ac dolor dictum dignissim.

Donec accumsan massa eget lobortis ornare. Morbi rutrum, est fringilla semper feugiat, mauris justo luctus neque, sit amet placerat dolor magna at tellus. Mauris eu scelerisque metus, elementum sollicitudin nisi. Aliquam luctus, massa a laoreet tincidunt, justo libero tristique orci, eu viverra ante dui vitae nunc. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed pellentesque nulla elit, vel fringilla urna condimentum nec. Pellentesque eget ultricies enim. Suspendisse dignissim posuere magna quis posuere. Etiam imperdiet metus non turpis mollis, sodales fringilla velit pellentesque.

Phasellus iaculis magna arcu, ut ultricies dui sagittis in. Mauris quis mi sit amet enim euismod viverra. Sed aliquam gravida ipsum, sit amet scelerisque nisi gravida ut. Vestibulum tortor erat, congue quis quam et, bibendum vulputate purus. Vivamus sagittis lectus in lorem sagittis, non rhoncus dui fermentum. Vivamus ut metus id eros pretium fermentum. Mauris massa magna, convallis at quam blandit, semper auctor velit. Nullam mauris mauris, tincidunt vel bibendum et, dictum a tortor. Nam eget dapibus odio. Proin feugiat, lacus vel elementum congue, ex metus fermentum ipsum, nec suscipit libero risus et eros. Pellentesque hendrerit a mauris non laoreet. Fusce pretium a libero lacinia fringilla. In hac habitasse platea dictumst. Aenean rutrum enim ligula, id convallis ipsum scelerisque a. Vivamus posuere lacus nisl, et cursus mi sollicitudin quis. Sed egestas ipsum sit amet mattis euismod.

Donec tristique luctus ex, sit amet pellentesque dolor. Mauris vulputate mauris id ligula lobortis finibus. Nunc id dapibus orci. Vivamus pellentesque imperdiet ligula, in euismod erat placerat vitae. Nam vel dapibus enim, quis porttitor erat. Cras id iaculis lacus. Suspendisse sit amet viverra sem. In gravida mauris mauris, sollicitudin ornare dolor ultrices sit amet. Pellentesque commodo vulputate urna, eget interdum ligula pulvinar vitae. Mauris dui ipsum, iaculis eu semper et, pulvinar in tortor. Nunc vehicula malesuada sagittis. Mauris turpis massa, tincidunt et iaculis sit amet, accumsan vitae dui. In vel nibh nulla. Phasellus mattis odio eu accumsan sodales. Donec accumsan augue ac aliquet tempus. Cras tellus lacus, consequat ac viverra eu, cursus at quam.

Sed sodales rhoncus tristique. Ut ut ultrices lacus, non ullamcorper magna. Aliquam pharetra, odio vel tempus iaculis, erat mauris cursus neque, vel faucibus neque velit tincidunt ligula. Donec congue erat tortor. Nullam nec leo quis massa auctor rhoncus eu eget orci. Maecenas accumsan sodales neque ac dapibus. Quisque tempor dignissim vehicula. Etiam ac nulla in lorem venenatis malesuada sed sed erat. Phasellus feugiat orci a lorem sodales, ut varius ante ultrices.

Mauris vestibulum mi nec lectus imperdiet, sit amet molestie purus fermentum. Integer mollis lectus in augue consequat, pharetra semper tellus tempus. Aliquam eu pretium nisi, in sodales sapien. Quisque ornare gravida elit quis sagittis. Sed a venenatis mauris. Nam pharetra semper risus at pretium. Ut vestibulum ipsum eget congue ornare. Cras vestibulum turpis ut nisi euismod ullamcorper. Phasellus lacus tortor, pellentesque sed leo id, lacinia fermentum est. Vestibulum diam metus, eleifend quis velit sit amet, scelerisque elementum elit. Quisque vel tempus nibh. Nullam tristique elit id elit faucibus, ac congue nisi bibendum.

Nullam euismod mollis enim id varius. Sed eget lorem quis erat lacinia consequat sed quis metus. Pellentesque ac tortor id magna pharetra placerat non non lacus. Nam placerat nunc at quam condimentum, nec faucibus libero tincidunt. Aliquam erat volutpat. Sed aliquam accumsan est sit amet euismod. Proin faucibus suscipit efficitur. Quisque fringilla, quam id fringilla tincidunt, augue dui imperdiet tellus, nec luctus diam tellus at massa. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam auctor est eget malesuada scelerisque. Duis vel pellentesque nibh, sit amet condimentum mauris. Duis facilisis sem accumsan dapibus porta. Quisque gravida turpis viverra, accumsan sem aliquam, auctor elit.

Vivamus consectetur dui nec lorem ullamcorper fringilla. Aenean rhoncus magna vel leo dapibus, ut luctus metus consequat. Donec vitae commodo leo. Quisque ornare, mauris nec luctus porttitor, purus sapien euismod libero, nec iaculis nisl libero id tellus. Nam dictum nibh sit amet orci tempus, nec tempus diam pharetra. Nam porttitor neque placerat nisi pharetra auctor. Cras ultricies malesuada felis at sodales. Donec in leo et nisl semper bibendum. Nulla non dictum nunc, ac congue risus.

Nam quis nibh feugiat, venenatis nunc ut, bibendum mauris. Praesent elementum, enim eget imperdiet condimentum, ligula lacus rhoncus est, in malesuada odio est ut purus. Nulla vel lacinia risus. Suspendisse sagittis lacus sed odio imperdiet bibendum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam nunc eros, convallis at aliquet ut, pharetra tincidunt nisl. Donec at neque sit amet leo tincidunt commodo eu et enim. Quisque elementum risus auctor pulvinar malesuada. Nullam rhoncus nisi ultrices diam finibus mollis. Fusce consequat magna id lorem pretium ultricies. Donec at convallis leo. Donec mi est, aliquet quis dui vel, gravida porta ligula. Phasellus imperdiet, quam eget pellentesque fermentum, enim mauris maximus sem, a accumsan ipsum leo quis massa. Fusce tristique felis quis odio auctor imperdiet. Nam pellentesque sem diam, non gravida ligula hendrerit quis.

Suspendisse vel metus at justo euismod aliquet nec id odio. Ut sed dignissim nunc, at vestibulum tellus. Duis convallis commodo egestas. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus fringilla ipsum vel mi pharetra dignissim. Pellentesque convallis sollicitudin purus, id accumsan ante viverra ut. Sed fringilla, tellus vel fringilla ultrices, purus lorem placerat eros, id pellentesque elit tellus vitae neque.

Fusce id diam dictum, commodo neque non, sagittis risus. Nulla pellentesque metus arcu, id blandit felis egestas ac. Cras malesuada commodo ipsum, consectetur porta erat volutpat vel. Fusce sit amet tincidunt risus, vel lacinia est. Mauris et vulputate ex, at consectetur tellus. Curabitur egestas nunc id nulla auctor malesuada. Ut condimentum, ex vitae mollis ullamcorper, mi magna accumsan lorem, ac accumsan enim lectus non lacus. Nunc vitae congue purus. Pellentesque quis placerat elit. Nullam eget mi enim. Nullam accumsan ipsum enim, eu hendrerit nunc mollis a. Nunc eget mauris consequat, rutrum lectus sit amet, ullamcorper neque. Quisque scelerisque odio vitae lacinia feugiat. Nunc sodales lectus at massa tempus malesuada vel sit amet dui.

Cras imperdiet tristique mauris. Nullam sit amet mollis magna. Etiam nec rutrum massa. Sed eget odio et mi blandit bibendum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent fermentum laoreet odio at fringilla. Sed malesuada eget felis a euismod. Mauris fringilla, quam vitae consectetur dictum, metus massa maximus felis, quis tempor sapien arcu vitae tortor. Pellentesque id ipsum sit amet ligula porttitor vulputate. Phasellus pulvinar ullamcorper est rhoncus tristique. Morbi laoreet ex sit amet semper facilisis. Etiam ornare tristique leo ac gravida. In et molestie tellus. Sed et lorem felis. Sed quis congue nunc. Morbi a sagittis sem.

Vestibulum vestibulum purus sed sapien tempor blandit. Nam sit amet nisi id lacus venenatis volutpat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque quis felis eu massa lacinia accumsan. Phasellus ac augue ultrices, gravida diam rutrum, tincidunt purus. Morbi efficitur tempus condimentum. Proin et diam at leo pharetra eleifend eu eu sem. Vestibulum sit amet suscipit ligula. Phasellus neque mi, sollicitudin vitae sem a, pretium lacinia augue. Suspendisse sodales mauris eu dui auctor convallis.

Pellentesque venenatis, odio ut iaculis luctus, ipsum est consectetur leo, et dictum massa metus sit amet diam. Nullam sed accumsan massa, hendrerit faucibus ante. Morbi a eros hendrerit, dapibus augue ac, blandit mauris. Nam dignissim lorem vitae efficitur scelerisque. In iaculis eros fermentum leo elementum, id rhoncus lectus imperdiet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Mauris fringilla erat non nisi blandit euismod. Ut at est et nunc iaculis rutrum vel ac ex. Fusce consequat varius quam sed semper. Donec nec augue sit amet erat suscipit commodo. Sed placerat, justo sed dapibus sagittis, quam tellus consectetur lacus, in porta lacus leo sit amet velit. Aenean sagittis ante nisi.

Morbi a pellentesque dolor. Phasellus erat risus, blandit sodales mi sit amet, venenatis mattis enim. Maecenas eu tellus tincidunt, blandit augue id, vulputate augue. Phasellus sit amet magna at lacus porttitor faucibus non eu massa. Aliquam nibh nibh, tincidunt et est quis, iaculis sodales felis. Ut ornare erat vitae iaculis auctor. Aliquam vitae est viverra, scelerisque magna nec, semper ligula. Sed facilisis tellus est, sit amet fringilla velit rhoncus non. Pellentesque hendrerit, lacus ut ultrices maximus, ex eros tempus turpis, sed vestibulum ipsum libero eu risus. Nulla rhoncus, neque eget accumsan laoreet, risus sapien varius purus, a ullamcorper metus felis at nunc. Nullam at consequat erat, ac viverra urna.
        </div>
    )
}

export default About;